name: CI

on:
  push:
  pull_request:

jobs:
  # Job 1: Проверка кода
  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Check package updates
        run: |
          UPDATES=$(pnpm run check-updates --silent)
          if [ -n "$UPDATES" ]; then
            echo "There are outdated packages:"
            echo "$UPDATES"
            exit 1
          fi
      - name: Lint
        run: pnpm run lint
      - name: Prettier check
        run: pnpm run prettier:check
      - name: Type check
        run: pnpm run typecheck

  # Job 2: Сборка и тесты
  build-and-test:
    runs-on: ubuntu-latest
    needs: code-check # запуск после успешного code-check
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Cache SWC
        uses: actions/cache@v3
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-swc-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-swc-
      - name: Build (prod)
        run: pnpm run build:prod
      - name: Run tests
        run: pnpm run test
