name: CI

on:
  push:
  pull_request:

env:
  HUSKY: 0

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node with cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check package updates
        run: |
          OUTDATED=$(pnpm outdated --json || true)
          if [ "$OUTDATED" != "{}" ] && [ -n "$OUTDATED" ]; then
            echo "There are outdated packages:"
            echo "$OUTDATED"
            exit 1
          fi

      - name: Lint
        run: pnpm run lint

      - name: Prettier check
        run: pnpm run prettier:check

      - name: Type check
        run: pnpm run typecheck

  build-and-test:
    runs-on: ubuntu-latest
    needs: code-check
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node with cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Ensure SWC cache folder exists
        run: mkdir -p node_modules/.cache

      - name: Cache SWC
        uses: actions/cache@v4
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-swc-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-swc-

      - name: Build (prod)
        run: pnpm run build:prod

      - name: Run tests
        run: pnpm run test
